export const products = [
  {
    id: 1,
    name: "Wireless Bluetooth Headphones",
    price: 120,
    category: "Electronics",
    brand: "SoundMax",
    description: "High-quality wireless headphones with noise cancellation and long battery life.",
    stock: 50,
    images: [
      "/bluetooth-headphone.jpg",
      "/bluetooth-earphone.jpg",
      "/bluetooth-headphone-black.jpg",
    ],
  },
  {
    id: 2,
    name: "Men's Running Sneakers",
    price: 85,
    category: "Fashion",
    brand: "RunPro",
    description: "Lightweight and comfortable running sneakers designed for daily workouts.",
    stock: 30,
    images: [
      "/sneakers-1.jpg",
      "/sneakers-2.jpg",
      "/sneakers-3.jpg",
      "/sneakers-4.jpg",
      "/sneakers-5.jpg",
    ],
  },
  {
    id: 3,
    name: "Smart Watch Series 9",
    price: 150,
    category: "Electronics",
    brand: "TechTime",
    description: "Advanced smartwatch with fitness tracking, heart rate monitoring, and GPS.",
    stock: 20,
    images: [
     "/smart-watch-series-1.jpg",
      "/smart-watch-series-2.jpg",
      "/smart-watch-series-3.jpg",
      "/smart-watch-series-4.jpg",
      "/smart-watch-series-5.jpg",
    ],
  },
  {
    id: 4,
    name: "Women's Designer Handbag",
    price: 200,
    category: "Fashion",
    brand: "StyleLux",
    description: "Elegant and spacious handbag made from premium materials for a luxurious feel.",
    stock: 15,
    images: [
      "/bluetooth-headphone.jpg",
      "/headphones2.jpg",
      "/headphones3.jpg",
      "/headphones4.jpg",
      "/headphones5.jpg",
    ],
  },
  {
    id: 5,
    name: "Women's Designer Handbag",
    price: 200,
    category: "Fashion",
    brand: "StyleLux",
    description: "Elegant and spacious handbag made from premium materials for a luxurious feel.",
    stock: 15,
    images: [
      "/bluetooth-headphone.jpg",
      "/headphones2.jpg",
      "/headphones3.jpg",
      "/headphones4.jpg",
      "/headphones5.jpg",
    ],
  },
  {
    id: 6,
    name: "Women's Designer Handbag",
    price: 200,
    category: "Fashion",
    brand: "StyleLux",
    description: "Elegant and spacious handbag made from premium materials for a luxurious feel.",
    stock: 15,
    images: [
      "/bluetooth-headphone.jpg",
      "/headphones2.jpg",
      "/headphones3.jpg",
      "/headphones4.jpg",
      "/headphones5.jpg",
    ],
  },
];
